plugin/BasicAssetLibrary/bal.py

Part of https://github.com/OpenAssetIO/OpenAssetIO/issues/660, reverts to using Python 3.7 style type hints, so we can maintain broader compatibility.
NB: This is demonstrated working in https://github.com/OpenAssetIO/OpenAssetIO/pull/694, we'll be shortly adding test CI test coverage to this repo. Wanted to make sure this parallel work didn't get lost.

[Resources] Use Python 3.7 type hints in `BasicAssetLibrary`

---

.github/workflows/code-quality.yml
plugin/BasicAssetLibrary/BasicAssetLibraryInterface.py
plugin/BasicAssetLibrary/__init__.py
plugin/BasicAssetLibrary/bal.py
tests/conftest.py
tests/fixtures.py
tests/requirements.txt
tests/test_bal.py

For pure python code, outside the main API, we use PEP8 with an extended line length of 99 + black formatting.

Add `pylint` and `black` CI checks

---

.github/workflows/build-wheels.yml
.github/workflows/deploy-pypi.yml
RELEASE_NOTES.md
pyproject.toml

Adopts the established pattern from other repos. A Test PyPI release is available here:
https://test.pypi.org/project/openassetio-manager-bal ([CI here](https://github.com/foundrytom/OpenAssetIO-Manager-BAL/actions/runs/3629498213)).
Closes #10

Publish BAL to PyPI

---

RELEASE_NOTES.md
plugin/openassetio_manager_bal/BasicAssetLibraryInterface.py
plugin/openassetio_manager_bal/bal.py
schema.json
tests/bal_business_logic_suite.py
tests/fixtures.py
tests/resources/library_business_logic_suite_related_references.json

Extends the BAL library to allow arbitrary relationships to be defined between entities. Relationships are un-versioned, and exist at the entity level to simplify understanding (and implementation).
Closes https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/issues/17.

Add support for `getRelatedReferences`

---

RELEASE_NOTES.md
pyproject.toml

Takes the opportunity to bump OpenAssetIO version to alpha.8 too.

[Release] Bump version to `v1.0.0-alpha.4`

---

plugin/openassetio_manager_bal/bal.py

We had originally decided to make this change to avoid potential foot-guns from to default list arguments. However, when it came to it, we weren't actually ever using the defaults.
Seems like a worthwhile change regardless as it is far more readable, and affords us the ability to include type hints.
Closes #20.

[Core] Use `dataclass` instead of `namedtuple`

---

README.md
RELEASE_NOTES.md
plugin/openassetio_manager_bal/bal.py
schema.json
tests/bal_business_logic_suite.py
tests/resources/library_business_logic_suite_var_expansion.json

Closes #22.
I didn't use `os.path.expandvars` in the end, for the noted reasons. Took the liberty of adding the lib path/dir implicit vars conceived after the initial chat too.

Add variable expansion to string trait property values.

---

.github/workflows/build-wheels.yml
.github/workflows/code-quality.yml
.github/workflows/test.yml
README.md
RELEASE_NOTES.md
pyproject.toml
requirements.txt

Having openassetio in the build dependencies for BAL was causing inflexibility, particularly in integrations CI as it was impossible to install it without also bringing in the PyPI OpenAssetIO. OpenAssetIO should more correctly be provided from the environment.
[#31](https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/issues/31)

[Build] Move pyproject dependency to requirements

---

.github/workflows/build-wheels.yml
.github/workflows/code-quality.yml
.github/workflows/test.yml
RELEASE_NOTES.md
plugin/openassetio_manager_bal/BasicAssetLibraryInterface.py
requirements.txt
tests/bal_business_logic_suite.py

Keeps parity with OpenAssetIO feature branch to facilitate e2e tests.
Experiments with using wheels from the OpenAssetIO feature branch to keep the tests working without the need for a custom OpenAssetIO build. Would be nice to wrap this up in an action that can detect the right platform/python version and install the right wheel.
Closes #34

Update to `getWithRelationship[s]`

---

.github/workflows/build-wheels.yml
.github/workflows/code-quality.yml
.github/workflows/test.yml
RELEASE_NOTES.md
plugin/openassetio_manager_bal/BasicAssetLibraryInterface.py
plugin/openassetio_manager_bal/bal.py
requirements.txt
tests/bal_business_logic_suite.py
tests/bal_functional_behaviour_suite.py
tests/fixtures.py

Provides a cleaned up version of [`feature/relatedReferencesRefactor`](https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/tree/feature/relatedReferencesRefactor), this should only be merged after https://github.com/OpenAssetIO/OpenAssetIO/pull/951.
Diff to the current feature branch [here](https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/compare/77c334a..3bd89ab).
Closes #42

Migrate `getRelatedReferences` to new signatures

---

tests/fixtures.py

In OpenAssetIO/OpenAssetIO#998 the `constants` module was migrated to C++ as a CPython submodule. This means, annoyingly, that we can no longer import objects `from` the `constants` module. Instead, we must import the `constants` module wholesale.

[Tests] Fix OpenAssetIO `constants` import

---

RELEASE_NOTES.md
tests/fixtures.py

A couple of `initialize` tests can now support fixtures. For some time we only had one setting for BAL, so presumably that was why some tests were legitimately skipped(?) Though some tests were clearly skipped in error, and one test simply doesn't exist in the API compliance suite (`test_when_settings_expanded_then_manager_settings_updated`).
One of the `getWithRelationship[s][Paged]` test cases was entirely missing fixtures, which was clearly a mistake.

[Tests] Add missing fixtures for API compliance suite

---

RELEASE_NOTES.md
plugin/openassetio_manager_bal/BasicAssetLibraryInterface.py
tests/bal_business_logic_suite.py
tests/bal_functional_behaviour_suite.py
tests/fixtures.py

Part of OpenAssetIO/OpenAssetIO#993
Note that this changes the (unreleased) behaviour of treating malformed entity references as `False` for existence, instead raising the appropriate `BatchElementError`.

Migrate entityExists to callback based API

---

RELEASE_NOTES.md
plugin/openassetio_manager_bal/BasicAssetLibraryInterface.py
tests/bal_business_logic_suite.py
tests/fixtures.py

Closes https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/issues/57.  See corresponding PR https://github.com/OpenAssetIO/OpenAssetIO/pull/1050
https://github.com/OpenAssetIO/OpenAssetIO/issues/1016 refined the Context access patterns to formalize the creation of "children" and other related entities via publish to an existing reference. BAL does not yet support this kind of creation, and so should error in the case.
So respond appropriately to Access mode in various API functions, by calling the provided error callback, except in the case of `managementPolicy` which responds with empty `TraitsData` objects (signifying "unmanaged").
Note that for consistency, this changes the error message output when attempting to `resolve` with `kWrite` access.

Validate access mode for API functions

---

RELEASE_NOTES.md
plugin/openassetio_manager_bal/BasicAssetLibraryInterface.py
tests/bal_business_logic_suite.py
tests/bal_functional_behaviour_suite.py

https://github.com/OpenAssetIO/OpenAssetIO/issues/1054 changed the signatures of key API methods so that the access is included as a parameter, instead of being hidden in the Context.
Closes #67

[Core] Update use of `Context.access` to direct args

---

RELEASE_NOTES.md
pyproject.toml
requirements.txt

This was causing issues as presenty, Media Creation has an install dependency on `openassetio`. We deliberately made this a soft dependency in BAL as it is always provided by the host.

[Core] Make `openassetio-mediacreation` a soft dependency

---

RELEASE_NOTES.md
plugin/openassetio_manager_bal/BasicAssetLibraryInterface.py
tests/bal_business_logic_suite.py

Adds hasCapability to BAL, along with a test case in the business logic suite.
Has a drop commit to https://github.com/OpenAssetIO/OpenAssetIO/pull/1126, and serves as the confirmation test.

Add hasCapability

---

RELEASE_NOTES.md
plugin/openassetio_manager_bal/BasicAssetLibraryInterface.py
tests/bal_business_logic_suite.py

Adds support for the ability to query a reference without dynamic behavior, so we can complete our working examples of MediaCreation defined versioning workflows.
Reviewer notes:
- The first commit is a refactor to make the code a little more amenable to extension
- The second adds the new functionality.
Closes #83

Add support for `StableReferenceRelationship` queries

---

RELEASE_NOTES.md
plugin/openassetio_manager_bal/BasicAssetLibraryInterface.py
plugin/openassetio_manager_bal/bal.py
schema.json
tests/bal_business_logic_suite.py
tests/resources/library_apiComplianceSuite.json
tests/resources/library_business_logic_suite_managementPolicy_custom.json

Closes #98.
OpenAssetIO/OpenAssetIO#1209 added the `kRequired` and `kManagerDriven` access mode options for `managementPolicy` queries, i.e. the subset of required traits for publishing to succeed, and the subset of traits that the manager wants to dictate during publishing, respectively.
For consistency, the `kWrite` access mode of `resolve` was renamed to `kManagerDriven`.
So add support for these access modes in an extensible way, by making use of the `kAccessNames` string mapping to allow the JSON database to specialise on any access mode to `managementPolicy` in a consistent way.
Also add support for `resolve` to take any access mode, with a new JSON field `supported_access_modes`, which is an iterable of supported modes (i.e. `kRead` and/or `kManagerDriven`), and which defaults to …

Support `kRequired` / `kManagerDriven` access modes

---

.github/workflows/build-wheels.yml
.github/workflows/code-quality.yml
.github/workflows/test.yml
RELEASE_NOTES.md
pyproject.toml

Now that OpenAssetIO v1.0.0-beta.2 is released, we can once again depend on the PyPI packages.

[CI] Retarget to OpenAssetIO release

---

RELEASE_NOTES.md
plugin/openassetio_manager_bal/BasicAssetLibraryInterface.py
tests/bal_business_logic_suite.py

Discovered whilst updating OpenAssetIO/OpenAssetIO-MediaCreation#69 after OpenAssetIO/OpenAssetIO#1217. The API docs for `resolve` say
> Only traits that are applicable to each entity, and for which the manager has data, will be imbued in the result.
However, if an entity in the JSON library has a trait as part of its trait set, but that trait has no properties (either because that trait has no associated properties, or because it's not set in the JSON), then it was imbued in the `TraitsData` regardless.

[Core] Fix resolve when trait has no properties

---

.github/workflows/code-quality.yml
RELEASE_NOTES.md

https://github.com/OpenAssetIO/OpenAssetIO/issues/737
Validate that markdown links are valid in CI.

[CI] Add Markdown links check

---

.github/workflows/build-wheels.yml
.github/workflows/code-quality.yml
.github/workflows/test.yml
RELEASE_NOTES.md
plugin/openassetio_manager_bal/BasicAssetLibraryInterface.py
plugin/openassetio_manager_bal/bal.py
pyproject.toml
schema.json
tests/bal_business_logic_suite.py
tests/fixtures.py
tests/resources/library_apiComplianceSuite.json
tests/resources/library_business_logic_suite_managementPolicy_custom.json

Closes #90 #92. 
Error during publishing (`preflight` and `register`) if the provided trait set is incompatible with `managementPolicy` or `entityTraits` (with `kWrite` access mode).
Add access mode to `EntityInfo`, for use in JSON DB queries. Default to ignoring access mode and returning the same data (from the entity `"versions"` list) for all access modes.
Add new `"exceptions"` option alongside an entity `"versions"` list in the JSON database. The `"exceptions"` object is a mapping of (stringified) access mode to entity data, overriding lookup in the `"versions"` list. 
In the new `"exceptions"` mapping, use the special value of `null` to mean the entity doesn't 'exist' for that access mode. Use the special value of empty dict `{}` to mean the entity exists but is inaccessible for …

Support entity access policies

---

.github/workflows/test.yml
RELEASE_NOTES.md
plugin/openassetio_manager_bal/bal.py
tests/bal_business_logic_suite.py
tests/resources/library_business_logic_suite_var_expansion.json

Closes #109. We should not be percent-decoding URLs fetched from the JSON DB before passing to the host, since other functions that consume the returned URL will most likely expect the URL to be percent-encoded.
In order to allow for upward traversals to be used in `file://` URLs in the DB (in particular, useful for e.g.
`${bal_library_dir_url}/../path/to/file`) we needed to parse the URL to treat as a path, resolve the upward traversals (since they are invalid in URLs according to `FileUrlPathConverter`), then reconstruct the URL. Unfortunately in doing this we also percent-decoded the URL and didn't re-encode it.
Passing the decoded URL to `FileUrlPathConverter.pathFromUrl` would then do a second round of percent-decoding, possibly decoding what should have been left as a %-sign.
So …

[Core] Don't %-decode file URLs from DB

---

plugin/openassetio_manager_bal/BasicAssetLibraryInterface.py
tests/fixtures.py

Part of OpenAssetIO/OpenAssetIO#1202.
Disallowing unrecognized settings almost certainly precludes using BAL as part of a hybrid plugin, since it is likely the other constituent plugins will have different settings keys, and the hybrid plugin system will pass the same settings dict to all child plugins.
As a result, the corresponding test in the API compliance suite will be removed from the core OpenAssetIO distribution, effectively relaxing the restriction that unrecognized keys should trigger an exception.
So remove the check for unknown settings keys, and corresponding API compliance suite fixtures.

Allow `initialize` with unrecognized settings

---

RELEASE_NOTES.md
plugin/openassetio_manager_bal/BasicAssetLibraryInterface.py
schema.json
tests/bal_business_logic_suite.py
tests/resources/library_business_logic_suite_capabilities_all.json
tests/resources/library_business_logic_suite_capabilities_minimal.json
tests/resources/library_business_logic_suite_capabilities_none.json

Closes #84. Host applications must be able to tolerate manager plugins that do not support the full suite of (optional) capabilities that a manager may implement. However, there was no way for hosts to use BAL to test their logic for dealing with different combinations of capabilities.
In addition, configurable capabilities are required to enable e2e testing of the capability-based routing used by the upcoming hybrid plugin system (see OpenAssetIO/OpenAssetIO#1202).
So add a simple way to override the default set of capabilities reported by BAL, by adding an optional "capabilities" list element to the library, where each element is a stringified capability, as defined in `kCapabilityNames`. Presence of a capability in this list indicates that it is supported. If the list is not found, …

Configurable `hasCapability` responses

---

RELEASE_NOTES.md
pyproject.toml

Discovered during OpenAssetIO/OpenAssetIO#1311.
Since #84, BAL's tests make use of the newer `getWithRelationship` signatures and so fail if OpenAssetIO 1.0.0-beta.2.1 or earlier is installed.
This isn't an incompatibility in BAL itself, just its tests. We could either:
* Rewrite the tests to use the older API.
* Bump the minimum supported version of OpenAssetIO
* Ignore the failure, since it's only tests.
Ignoring the test failure is potentially dangerous, in case the expected failure is masking a real issue.
Rewriting the tests would be the best option, but requires development effort. Given that we're still in beta, the low-effort choice of bumping the minimum OpenAssetIO version seems the best pragmatic option.

[Build] Bump OpenAssetIO to 1.0.0-beta.2.2

---

RELEASE_NOTES.md
pyproject.toml

Part of OpenAssetIO/OpenAssetIO#1311. Deprecated aliases have been removed from the latest OpenAssetIO, but the version of MediaCreation that was pinned in `pyproject.toml` still used them.
So bump the version of MediaCreation to the latest.

[Build] Bump MediaCreation to 1.0.0-alpha.9

---

.github/workflows/build-wheels.yml
.github/workflows/code-quality.yml
.github/workflows/deploy-pypi.yml
.github/workflows/test.yml
RELEASE_NOTES.md
pyproject.toml

Part of OpenAssetIO/OpenAssetIO#1351. Use CI runner and Python version the best matches VFX Reference Platform CY24. Hence drop support for CY22.

Default to CY24 and drop support for CY22

---

plugin/openassetio_manager_bal/BasicAssetLibraryInterface.py
plugin/openassetio_manager_bal/bal.py
schema.json
tests/bal_business_logic_suite.py
tests/resources/library_apiComplianceSuite.json

Closes #53. Add support for the `defaultEntityReference` API method, which provides a way for hosts to get a "starting point" for further queries.
Add a new top-level dictionary to the JSON database `defaultEntities`, which has a mapping per access mode of trait set to entity reference.
If no matching trait set is found in the JSON database, then respond with `kInvalidTraitSet`. In real-world managers, an unrecognised trait set would probably elicit a response of `None` (for "no appropriate default"), rather than exception. But here we make a `None` response explicit by specifying `null` in the JSON database.

Support `defaultEntityReference`

---

RELEASE_NOTES.md
plugin/openassetio_manager_bal/BasicAssetLibraryInterface.py
plugin/openassetio_manager_bal/bal.py
schema.json
tests/bal_business_logic_suite.py
tests/resources/library_apiComplianceSuite.json

Part of testing TheFoundryVisionmongers/KatanaOpenAssetIO#4.
BAL would error when performing relationship queries with a non-`kRead` access mode. However, such queries are valid for publishing workflows and so must be supported in order to test host applications.
So add an optional `"access"` flag that can be added to relationship definitions in the JSON database, overriding the default `kRead` access, and limiting that relationship to the specific access mode.
Hence no longer error when responding to relationship queries for non-`kRead` access modes (the default response instead being an empty set of entity references).
Additionally, if a version relationship trait set is specified in the JSON database, then prefer that over the built-in versioning behaviour. A long term goal would be to …

Add relationship access and version overrides
